spring:
  datasource:
    username: root
    password: TiMpWfM5-
    url: jdbc:mysql://localhost:3306/unittest
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml

junit:
  jupiter:
    displayname:
      generator:
        default: org.junit.jupiter.api.DisplayNameGenerator$ReplaceUnderscores